server:
  shutdown: graceful


spring:
  jpa:
    open-in-view: false
    properties:
      jakarta:
        persistence:
          sharedCache:
            mode: ALL

jwt:
  secret-key: fadsdnfiew232938rfksl#$@#dsfsdnf
  issuer: han
  expired-time: 180000 # 3분